{
 "title": "Top by Prefixes",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router_name",
    "label": "Filter by Router",
    "query": "select name as value from routers"
   }
  ]
 },
 "panels": [
  {
   "title": "Updates & Withdrawals (changes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nfloor(unix_timestamp(interval_time)) as time_sec,\nsum(updates) as value,\n  'updates' as metric\nFROM gen_chg_stats_bypeer s\n  STRAIGHT_JOIN v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n  AND routername in ($router_name)\nGROUP BY interval_time\nORDER BY interval_time ASC\n\n"
    },
    {
     "rawSql": "SELECT\nfloor(unix_timestamp(interval_time)) as time_sec,\nsum(withdraws) as value,\n'withdraws' as metric\nFROM gen_chg_stats_bypeer s\n  STRAIGHT_JOIN v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n  AND routername in ($router_name)\nGROUP BY interval_time\nORDER BY interval_time ASC\n"
    }
   ]
  },
  {
   "title": "Updates By Router",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Updates" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    floor(unix_timestamp(interval_time)) as time_sec,\n    updates as value,\n    p.RouterName as metric\n  FROM gen_chg_stats_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n    AND p.routername IN ($router_name)\n  order by interval_time asc\n\n"
    }
   ]
  },
  {
   "title": "Withdraws  By Router",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none", "label": "Withdraws" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    floor(unix_timestamp(interval_time)) as time_sec,\n    withdraws as value,\n    p.RouterName as metric\n  FROM gen_chg_stats_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND p.routername IN ($router_name)\n  order by interval_time asc\n\n"
    }
   ]
  },
  {
   "title": "Updates by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "Count of Updates" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    floor(unix_timestamp(interval_time)) as time_sec,\n    updates as value,\n    p.PeerName as metric\n  FROM gen_chg_stats_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND p.routername IN ($router_name)\n  order by interval_time asc\n"
    }
   ]
  },
  {
   "title": "Withdraws  by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "Count of Updates" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    floor(unix_timestamp(interval_time)) as time_sec,\n    withdraws as value,\n    p.PeerName as metric\n  FROM gen_chg_stats_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND p.routername IN ($router_name)\n  order by interval_time asc\n"
    }
   ]
  },
  {
   "title": "Top Updates by Prefix",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Updates" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    floor(unix_timestamp(interval_time)) as time_sec,\n    sum(updates) as value,\n    concat(prefix,'/', prefix_len) as metric\n  FROM gen_chg_stats_byprefix l use index (primary)\n  WHERE $__timeFilter(interval_time)\n      AND peer_hash_id in (SELECT peer_hash_id from v_peers where routername in ($router_name))\n  GROUP BY metric\n  order by value desc\nLIMIT 20"
    }
   ]
  },
  {
   "title": "Top Withdraws by Prefix",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none", "label": "Withdraws" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n    floor(unix_timestamp(interval_time)) as time_sec,\n    sum(withdraws) as value,\n    concat(prefix,'/', prefix_len) as metric\n  FROM gen_chg_stats_byprefix l use index (primary)\n  WHERE $__timeFilter(interval_time)\n      AND peer_hash_id in (SELECT peer_hash_id from v_peers where routername in ($router_name))\n  GROUP BY metric\n  order by value desc\nLIMIT 20;\n"
    }
   ]
  }
 ]
}