{
 "title": "Inventory",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Router Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  floor(UNIX_TIMESTAMP(timestamp)) as time_sec,\n  count(*) as value,\n  if (isconnected, 'UP', 'DOWN') as metric\nFROM routers\n  group by isconnected\n"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "select r.timestamp,r.name,ip_address,if (isConnected, 'UP', 'DOWN') as state,\n    count(*) as peers,description,isConnected\n  from routers r\n  JOIN bgp_peers p on (r.hash_id = p.router_hash_id)\n  GROUP BY r.name;"
    }
   ]
  },
  {
   "title": "Peer Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  floor(UNIX_TIMESTAMP(timestamp)) as time_sec,\n  count(*) as value,\n  if (state, 'UP', 'DOWN') as metric\nFROM bgp_peers\n  group by metric"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "rawSql": "select RouterName,PeerName,PeerIP,PeerASN,if(isUp, 'UP', 'DOWN') as State,LastModified,isUp from v_peers;\n"
    }
   ]
  }
 ]
}