{
 "title": "BGP Sec: RPKI & IRR",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Prefixes in Violations",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT  floor(UNIX_TIMESTAMP(timestamp)) as time_sec, 'rpki' as metric, count(*) as value\n  FROM gen_prefix_validation\n  WHERE recv_origin_as != rpki_origin_as and rpki_origin_as is not null\nUNION (\n  SELECT\n     floor(UNIX_TIMESTAMP(timestamp)) as time_sec,\n    'irr' as metric,\n    count(*) as value\n  FROM gen_prefix_validation\n  WHERE recv_origin_as != irr_origin_as and irr_origin_as is not null\n)\nUNION (\n  SELECT\n     floor(UNIX_TIMESTAMP(timestamp)) as time_sec,\n    'no_rpki_irr' as metric,\n    count(*) as value\n  FROM gen_prefix_validation\n  WHERE irr_origin_as is null and rpki_origin_as is null\n);\n\n"
    }
   ]
  },
  {
   "title": "Prefixes in RPKI and IRR",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT  floor(UNIX_TIMESTAMP(timestamp)) as time_sec, 'rpki' as metric, count(*) as value\n  FROM gen_prefix_validation\n  WHERE rpki_origin_as is not null\nUNION (\n  SELECT\n     floor(UNIX_TIMESTAMP(timestamp)) as time_sec,\n    'irr' as metric,\n    count(*) as value\n  FROM gen_prefix_validation\n  WHERE irr_origin_as is not null\n)\nUNION (\n  SELECT\n     floor(UNIX_TIMESTAMP(timestamp)) as time_sec,\n    'total' as metric,\n    count(distinct prefix,prefix_len) as value\n  FROM gen_prefix_validation\n);\n\n"
    }
   ]
  },
  {
   "title": "Updates in Violation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  (floor(UNIX_TIMESTAMP(timestamp) / 300) * 300) as time_sec,\n  count(*) as value,\n  'rpki' as metric\nFROM gen_prefix_validation\nWHERE $__timeFilter(timestamp)\n    AND recv_origin_as != rpki_origin_as and rpki_origin_as is not null\n  GROUP BY (floor(UNIX_TIMESTAMP(timestamp) / 300) * 300)\nUNION (\nSELECT\n  (floor(UNIX_TIMESTAMP(timestamp) / 300) * 300) as time_sec,\n  count(*) as value,\n  'irr' as metric\nFROM gen_prefix_validation\nWHERE $__timeFilter(timestamp)\n    AND recv_origin_as != irr_origin_as and irr_origin_as is not null\nGROUP BY (floor(UNIX_TIMESTAMP(timestamp) / 300) * 300)\n)\nORDER BY time_sec ASC"
    }
   ]
  },
  {
   "title": "Prefixes in Violation of RPKI",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select timestamp as Time, \n     concat(inet6_ntoa(prefix), '/', prefix_len) as Prefix,\n     recv_origin_as as `Received Origin`,\n     rpki_origin_as as `Expected Origin`\n  FROM gen_prefix_validation\n  WHERE recv_origin_as != rpki_origin_as and rpki_origin_as is not null;"
    }
   ]
  },
  {
   "title": "Prefixes in Violation of IRR (filtered by time range)",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select timestamp as Time, \n     concat(inet6_ntoa(prefix), '/', prefix_len) as Prefix,\n     recv_origin_as as `Received Origin`,\n     irr_origin_as as `Expected Origin`,\n     irr_source as `IRR Source`\n  FROM gen_prefix_validation\n  WHERE recv_origin_as != irr_origin_as and irr_origin_as is not null\n    and $__timeFilter(timestamp)"
    }
   ]
  }
 ]
}