{
 "title": "Prefix History (by Prefix)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prefix", "label": "Prefix", "query": "${VAR_PREFIX}" },
   { "name": "prefix_len", "label": "Prefix Length", "query": "${VAR_PREFIX_LEN}" },
   { "name": "router_name", "label": "Router", "query": "select name from routers" }
  ]
 },
 "panels": [
  {
   "title": "Prefix Updates & Withdrawals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  floor(UNIX_TIMESTAMP(interval_time)) as time_sec,\n  sum(updates) as value,\n  'Updates' as metric\nFROM gen_chg_stats_byprefix s use index (idx_prefix_full,primary)\nWHERE $__timeFilter(interval_time)\n   AND prefix = \"$prefix\" and prefix_len = $prefix_len\n   AND s.peer_hash_id IN (SELECT peer_hash_id\n                            from v_peers\n                            where routername IN ($router_name))\n\ngroup by interval_time\nORDER BY interval_time ASC\n"
    },
    {
     "rawSql": "SELECT\n  floor(UNIX_TIMESTAMP(interval_time)) as time_sec,\n  sum(withdraws) as value,\n  'Withdraws' as metric\nFROM gen_chg_stats_byprefix s use index (idx_prefix_full,primary)\nWHERE $__timeFilter(interval_time)\n   AND prefix = \"$prefix\" and prefix_len = $prefix_len\n   AND s.peer_hash_id IN (SELECT peer_hash_id\n                            from v_peers\n                            where routername IN ($router_name))\ngroup by interval_time\nORDER BY interval_time ASC\n"
    }
   ]
  },
  {
   "title": "Changes by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  floor(UNIX_TIMESTAMP(interval_time)) as time_sec,\n  sum(updates) + sum(withdraws) as value,\n  left(PeerName,32) as metric\nFROM gen_chg_stats_byprefix l\n  STRAIGHT_JOIN v_peers p ON (l.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n   AND prefix = \"$prefix\" and prefix_len = $prefix_len\n   AND p.routername in ($router_name)\nGROUP BY l.interval_time,l.peer_hash_id\nORDER BY interval_time ASC\n\n"
    }
   ]
  },
  {
   "title": "Prefix History",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT h.timestamp,p.RouterName,p.PeerName,p.PeerASN,h.prefix,h.prefix_len,\n        'UPDATE' as STATE, a.as_path,a.community_list,a.local_pref,a.med\n   FROM\n    (SELECT timestamp,peer_hash_id,path_attr_hash_id,prefix,prefix_len,origin_as\n        FROM path_attr_log use index (idx_ts,idx_prefix)\n        WHERE $__timeFilter(timestamp)\n          AND prefix = \"$prefix\" and prefix_len = $prefix_len\n        ORDER BY timestamp desc\n        LIMIT 3000) h\n    STRAIGHT_JOIN v_peers p ON (p.peer_hash_id = h.peer_hash_id)\n    STRAIGHT_JOIN path_attrs a ON (a.hash_id = h.path_attr_hash_id)\n  WHERE p.routername in ($router_name)\nunion (\nSELECT h.timestamp,p.RouterName,p.PeerName,p.PeerASN,h.prefix,h.prefix_len,\n        'WITHDRAWAL' as STATE, a.as_path,a.community_list,a.local_pref,a.med\n   FROM\n    (SELECT timestamp,peer_hash_id,path_attr_hash_id,prefix,prefix_len,origin_as\n        FROM withdrawn_log use index (idx_ts,idx_prefix)\n        WHERE $__timeFilter(timestamp)\n          AND prefix = \"$prefix\" and prefix_len = $prefix_len\n        ORDER BY timestamp desc\n        LIMIT 2000) h\n    STRAIGHT_JOIN v_peers p ON (p.peer_hash_id = h.peer_hash_id)\n    STRAIGHT_JOIN path_attrs a ON (a.hash_id = h.path_attr_hash_id)\n  WHERE p.routername in ($router_name)\n  )"
    }
   ]
  }
 ]
}