{
 "title": "Prefix History (by ASN)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "origin_as", "label": "Origin ASN", "query": "${VAR_ORIGIN_AS}" },
   { "name": "router_name", "label": "Router", "query": "select name from routers" }
  ]
 },
 "panels": [
  {
   "title": "Prefix Updates & Withdrawals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  floor(UNIX_TIMESTAMP(interval_time)) as time_sec,\n  sum(updates) as value,\n  'Updates' as metric\nFROM gen_chg_stats_byasn s\n    STRAIGHT_JOIN v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n   AND origin_as = $origin_as\n   AND p.routername IN ($router_name)\ngroup by interval_time\nORDER BY interval_time ASC\n\n"
    },
    {
     "rawSql": "SELECT\n  floor(UNIX_TIMESTAMP(interval_time)) as time_sec,\n  sum(withdraws) as value,\n  'Withdraws' as metric\nFROM gen_chg_stats_byasn s\n    STRAIGHT_JOIN v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n   AND origin_as = $origin_as\n   AND p.routername IN ($router_name)\ngroup by interval_time\nORDER BY interval_time ASC"
    }
   ]
  },
  {
   "title": "Changes by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  floor(UNIX_TIMESTAMP(interval_time)) as time_sec,\n  sum(updates) + sum(withdraws) as value,\n  left(PeerName,32) as metric\nFROM gen_chg_stats_byasn l\n  STRAIGHT_JOIN v_peers p ON (l.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n   AND origin_as = $origin_as\n   AND p.routername in ($router_name)\nGROUP BY l.interval_time,l.peer_hash_id\nORDER BY interval_time ASC"
    }
   ]
  },
  {
   "title": "Prefix History",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": " SELECT h.timestamp,p.RouterName,p.PeerName,p.PeerASN,h.prefix,h.prefix_len,\n        'UPDATE' as state,a.as_path,a.community_list,a.local_pref,a.med\n   FROM\n    (SELECT timestamp,peer_hash_id,path_attr_hash_id,prefix,prefix_len,origin_as\n        FROM path_attr_log\n        WHERE $__timeFilter(timestamp)\n          AND origin_as = $origin_as\n        ORDER BY timestamp desc\n        LIMIT 3000) h\n    STRAIGHT_JOIN v_peers p ON (p.peer_hash_id = h.peer_hash_id)\n    STRAIGHT_JOIN path_attrs a ON (a.hash_id = h.path_attr_hash_id)\n  WHERE p.routername in ($router_name)\nUNION (\n SELECT h.timestamp,p.RouterName,p.PeerName,p.PeerASN,h.prefix,h.prefix_len,\n        'WITHDRAWAL' as state,a.as_path,a.community_list,a.local_pref,a.med\n   FROM\n    (SELECT timestamp,peer_hash_id,path_attr_hash_id,prefix,prefix_len,origin_as\n        FROM path_attr_log\n        WHERE $__timeFilter(timestamp)\n          AND origin_as = $origin_as\n        ORDER BY timestamp desc\n        LIMIT 2000) h\n    STRAIGHT_JOIN v_peers p ON (p.peer_hash_id = h.peer_hash_id)\n    STRAIGHT_JOIN path_attrs a ON (a.hash_id = h.path_attr_hash_id)\n  WHERE p.routername in ($router_name)\n)"
    }
   ]
  }
 ]
}