{
 "title": "Prefix History (by Peer)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router_name",
    "label": "Router",
    "query": "select distinct routername from v_peers"
   },
   {
    "name": "peer_name",
    "label": "Peer",
    "query": "select peername from v_peers where routername = '[[router_name]]'"
   }
  ]
 },
 "panels": [
  {
   "title": "Prefix Advertisements & Withdrawals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n  sum(updates) as updates, sum(withdraws) as withdraws\nFROM stats_chg_bypeer s\nWHERE $__timeFilter(interval_time)\n   AND s.peer_hash_id IN (SELECT peer_hash_id\n                            from v_peers\n                            where peername = '$peer_name')\n\ngroup by interval_time\nORDER BY interval_time ASC\n"
    }
   ]
  },
  {
   "title": "Changes by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n  sum(updates) + sum(withdraws) as value,\n  left(PeerName,32) as metric\nFROM stats_chg_bypeer l\n  JOIN v_peers p ON (l.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n   AND p.peername = '$peer_name'\nGROUP BY l.interval_time,peername\nORDER BY interval_time ASC\n\n"
    }
   ]
  },
  {
   "title": "Prefix History",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": " select lastmodified,event,routername,peername,prefix,\n        origin_as,nh,as_path,communities \n    from v_ip_routes_history \n    where  $__timeFilter(lastmodified)\n      AND peername = '$peer_name'\n    order by lastmodified desc,id desc\n    limit 1000;"
    }
   ]
  }
 ]
}