{
 "title": "Prefix History (by Prefix)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prefix", "label": "Prefix", "query": "66.114.160.0/20" }
  ]
 },
 "panels": [
  {
   "title": "Current RIB State",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select lastmodified,CASE WHEN iswithdrawn THEN 'Withdrawn' ELSE 'Active' END as state,routername,peername,prefix,prefixlen,\n        origin_as,med,localpref,nh,as_path,communities \n    from v_ip_routes \n    where prefix = '[[prefix]]'\n"
    }
   ]
  },
  {
   "title": "Prefix Advertisements & Withdrawals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n  sum(updates) as updates, sum(withdraws) as withdraws\nFROM stats_chg_byprefix s\nWHERE $__timeFilter(interval_time)\n   AND s.prefix = '[[prefix]]'\n\ngroup by interval_time\nORDER BY interval_time ASC\n"
    }
   ]
  },
  {
   "title": "Changes by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n  sum(updates) + sum(withdraws) as value,\n  left(PeerName,32) as metric\nFROM stats_chg_byprefix s\n  JOIN v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n   AND s.prefix = '[[prefix]]'\nGROUP BY s.interval_time,peername\nORDER BY interval_time ASC\n\n"
    }
   ]
  },
  {
   "title": "Prefix History",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": " select lastmodified,event,routername,peername,prefix,nh,\n        origin_as,as_path,communities \n    from v_ip_routes_history \n    where  $__timeFilter(lastmodified)\n      AND prefix = '[[prefix]]'\n      \n    order by lastmodified desc,id desc\n    limit 1000;"
    }
   ]
  }
 ]
}