{
 "title": "LS Links",
 "tags": [ "obmp-linkstate" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "peer_hash",
    "label": "BGP Peer",
    "query": "SELECT __text,__value FROM (\n    select peername as __text, peer_hash_id as __value, count(*) as count\n    from v_ls_nodes\n   group by peername,peer_hash_id) d\nwhere count > 10\n   "
   },
   {
    "name": "local_node_hash_id",
    "label": "ISIS Node",
    "query": "select name as __text, hash_id as __value from ls_nodes where peer_hash_id = '$peer_hash' and not igp_router_id ~ '\\..[1-9A-F]00$'"
   },
   {
    "name": "local_node_name",
    "query": "select name from ls_nodes where hash_id = '$local_node_hash_id' and peer_hash_id = '$peer_hash'"
   }
  ]
 },
 "panels": [
  {
   "title": "Link States",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select floor(extract(epoch from max(timestamp))) as time,\n       count(*) as value, CASE WHEN iswithdrawn THEN 'WITHDRAWN' ELSE 'ACTIVE' END as metric\nfrom ls_links\nwhere local_node_hash_id = '$local_node_hash_id'\n  AND peer_hash_id = '$peer_hash'\ngroup by iswithdrawn\norder by time\n"
    }
   ]
  },
  {
   "title": "Links by Type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select floor(extract(epoch from max(timestamp))) as time,\n       count(*) as value, CASE WHEN mt_id = 2 THEN 'IPv6' ELSE 'IPv4' END as metric\nfrom ls_links\nwhere local_node_hash_id = '$local_node_hash_id'\n  AND peer_hash_id = '$peer_hash'\ngroup by mt_id\norder by time\n"
    }
   ]
  },
  {
   "title": "$local_node_name Links",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT state,local_router_name,local_igp_routerid,remote_router_name,remote_igp_routerid,mt_id,igp_metric,protocol, timestamp, seq\n  FROM v_ls_links\n  WHERE local_node_hash_id = '$local_node_hash_id'\n    AND peer_hash_id = '$peer_hash'"
    }
   ]
  }
 ]
}