{
 "title": "LS Nodes",
 "tags": [ "obmp-linkstate" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "peer_hash",
    "label": "BGP Peer",
    "query": "SELECT __text,__value FROM (\n    select peername as __text, peer_hash_id as __value, count(*) as count\n    from v_ls_nodes\n   group by peername,peer_hash_id) d\nwhere count > 10\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\n  FROM ls_nodes where peer_hash_id = '$peer_hash';"
    }
   ]
  },
  {
   "title": "Link States",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select floor(extract(epoch from max(timestamp))) as time,\n      count(*) as count, \n       CASE WHEN iswithdrawn THEN 'WITHDRAWN' ELSE 'ACTIVE' END as metric\nfrom ls_links\nwhere peer_hash_id = '$peer_hash'\ngroup by iswithdrawn\norder by time\n"
    }
   ]
  },
  {
   "title": "Links by Type",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select floor(extract(epoch from max(timestamp))) as time,\n       count(*) as count, \n       CASE WHEN mt_id = 2 THEN 'IPv6' ELSE 'IPv4' END as metric\nfrom ls_links \nwhere peer_hash_id = '$peer_hash'\ngroup by metric\norder by time\n"
    }
   ]
  },
  {
   "title": "Backbone ISIS Nodes",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT state, nodename, routerid, protocol, timestamp, seq\n  FROM v_ls_nodes\n  where peer_hash_id = '$peer_hash'\n\n       "
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 }, "options": { "content": "\n\n" } }
 ]
}