{
 "title": "BGP Sec: Hijack/Leak",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "asn", "label": "ASN", "query": "${VAR_ASN}" }
  ]
 },
 "panels": [
  {
   "title": "Transit Leak/Hijacks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"prefix\")) FROM \"alerts\"  WHERE (\"tag-type\" = 'TRANSIT_LEAK' OR \"tag-type\" = 'TRANSIT_HIJACK') AND  $timeFilter GROUP BY time($__interval);",
     "rawSql": "SELECT\nfloor(UNIX_TIMESTAMP(period_ts)) as time_sec,\ncount(distinct prefix_bin,prefix_len,period_ts) as value,\nwatcher_rule_name as metric\nFROM watcher_prefix_log\nWHERE watcher_rule_num = 2 and $__timeFilter(period_ts) AND ($asn_num = \"All\" or origin_as = $asn_num)\nGROUP BY period_ts,watcher_rule_num\nORDER BY last_ts ASC\n"
    }
   ]
  },
  {
   "title": "Upstream Leak/Hijacks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"prefix\")) FROM \"alerts\"  WHERE (\"tag-type\" = 'UPSTREAM_LEAK' or \"tag-type\" = 'UPSTREAM_HIJACK') AND  $timeFilter GROUP BY time($__interval);",
     "rawSql": "SELECT\nfloor(UNIX_TIMESTAMP(period_ts)) as time_sec,\ncount(distinct prefix_bin,prefix_len,period_ts) as value,\nwatcher_rule_name as metric\nFROM watcher_prefix_log\nWHERE watcher_rule_num = 3 and $__timeFilter(period_ts) AND ($asn_num = \"All\" or origin_as = $asn_num)\nGROUP BY period_ts,watcher_rule_num\nORDER BY last_ts ASC\n"
    }
   ]
  },
  {
   "title": "Origin HiJacks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(distinct(\"prefix\")) FROM \"alerts\"  WHERE \"tag-type\" = 'ORIGIN_HIJACK' AND  $timeFilter GROUP BY time($__interval);\n",
     "rawSql": "SELECT\nfloor(UNIX_TIMESTAMP(period_ts)) as time_sec,\ncount(distinct prefix_bin,prefix_len,period_ts) as value,\nwatcher_rule_name as metric\nFROM watcher_prefix_log\nWHERE watcher_rule_num = 1 and $__timeFilter(period_ts) AND ($asn_num = \"All\" or origin_as = $asn_num)\nGROUP BY period_ts,watcher_rule_num\nORDER BY last_ts ASC\n"
    }
   ]
  },
  {
   "title": "Alert Counts",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "alerts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {
     "alias": "prefixes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "SELECT count(distinct(\"prefix\")) FROM \"10weeks\".\"alerts\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "prefix" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "origins",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "SELECT count(distinct(\"origin_as\")) FROM \"10weeks\".\"alerts\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "origin_as" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Offending ASNs",
   "type": "graph",
   "description": "Count of alerts by offending ASNs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Count of Alerts" }
   ],
   "targets": [
    {
     "alias": "asn: [[tag_tag-offending_asn]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag-offending_asn" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "SELECT count(\"message\") as items FROM \"10weeks\".\"alerts\" WHERE  $timeFilter GROUP BY time(60s),\"tag-offending_asn\" fill(none) ",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "slimit": "25",
     "tags": [
      { "key": "tag-offending_asn", "operator": "<>", "value": "''" }
     ]
    }
   ]
  },
  {
   "title": "Monitored ASNs",
   "type": "graph",
   "description": "Count of alerts by monitored ASNs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "Count of Alerts" }
   ],
   "targets": [
    {
     "alias": "asn: [[tag_tag-monitored_asn]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "tag-offending_asn" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "SELECT count(\"message\") as items FROM \"10weeks\".\"alerts\" WHERE  $timeFilter GROUP BY time(60s),\"tag-monitored_asn\" fill(none) ",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "slimit": "25",
     "tags": [
      { "key": "tag-offending_asn", "operator": "<>", "value": "''" }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "alerts",
     "query": "SELECT \"tag-type\" as \"type\",\"monitored_asname\" as \"monitored\",\"offending_asname\" as \"offending\",\"message\" as analysis FROM \"10weeks\".\"alerts\" WHERE $timeFilter AND ('[[asn]]' = 'all' OR \"tag-affected_asn\" = '[[asn]]' OR \"tag-monitored_asn\" = '[[asn]]') ORDER BY time DESC limit 2000;",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}