{
 "title": "Prefix History (by Prefix) L3VPN",
 "tags": [ "obmp-l3vpn" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router_hash",
    "label": "Router",
    "query": "select routername as __text, router_hash_id as __value from v_peers where router_state = 'up' and recvcapabilities like '% afi=1 safi=128 %';\n"
   },
   {
    "name": "peer_hash",
    "label": "Peer",
    "query": "select peername as __text, peer_hash_id as __value from v_peers where router_hash_id in ($router_hash) and peer_state = 'up' and recvcapabilities like '% afi=1 safi=128 %';"
   },
   { "name": "limit", "label": "Limit", "query": "1000,3000,5000,8000,10000" },
   { "name": "input", "label": "Prefix", "query": "100.100.100.100" },
   {
    "name": "prefix_clause",
    "query": "select CASE WHEN '$input' != '-' THEN 'AND prefix = ''' || (\n               select prefix from l3vpn_rib \n                   where peer_hash_id in ($peer_hash) \n                           AND    ('$rd' = '-' OR rd = '$rd')\n                           AND prefix >>= (CASE WHEN '$input' != '-' THEN '$input' ELSE '0/0' END)::inet order by prefix desc limit 1)::text || ''''\n                                                        ELSE '' END;"
   },
   { "name": "rd", "label": "RD", "query": "-" }
  ]
 },
 "panels": [
  {
   "title": "Current RIB State",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select lastmodified,CASE WHEN iswithdrawn THEN 'Withdrawn' ELSE 'Active' END as state,routername,peername,prefix,prefixlen,\n        origin_as,med,localpref,nh,as_path,communities \n    from v_l3vpn_routes \n    where peer_hash_id in ($peer_hash) \n    ${prefix_clause:raw}\n    limit $limit\n"
    }
   ]
  },
  {
   "title": "Prefix Advertisements & Withdrawals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n  sum(updates) as updates, sum(withdraws) as withdraws\nFROM stats_l3vpn_chg_byprefix s\nWHERE $__timeFilter(interval_time)\n   AND peer_hash_id in ($peer_hash)\n   ${prefix_clause:raw}\n\ngroup by interval_time\nORDER BY interval_time ASC\n"
    }
   ]
  },
  {
   "title": "Changes by Peer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  interval_time as time,\n  sum(updates) + sum(withdraws) as value,\n  left(PeerName,32) as metric\nFROM stats_l3vpn_chg_byprefix s\n  JOIN v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n  AND s.peer_hash_id in ($peer_hash)\n  ${prefix_clause:raw}\n\nGROUP BY s.interval_time,peername\nORDER BY interval_time ASC\n\n"
    }
   ]
  },
  {
   "title": "Prefix History",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": " select lastmodified,event,routername,peername,prefix,nh,\n        origin_as,localpref,med,as_path,extcommunities,communities,largecommunities\n    from v_l3vpn_routes_history \n    where  $__timeFilter(lastmodified)\n     AND peer_hash_id in ($peer_hash)\n     ${prefix_clause:raw}\n      \n    order by lastmodified desc,id desc\n    limit $limit;"
    }
   ]
  }
 ]
}