{
 "title": "L3VPN RIB Browser",
 "tags": [ "obmp-l3vpn" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router_hash",
    "label": "Router",
    "query": "select routername as __text, router_hash_id as __value from v_peers where router_state = 'up' and  recvcapabilities like '% afi=1 safi=128 %';"
   },
   {
    "name": "peer_hash",
    "label": "Peer",
    "query": "select peername as __text, peer_hash_id as __value from v_peers where router_hash_id in ($router_hash) and  recvcapabilities like '% afi=1 safi=128 %';"
   },
   { "name": "rd", "label": "RD", "query": "-" },
   { "name": "limit", "label": "Limit", "query": "1000,3000,5000,8000,10000" },
   {
    "name": "state",
    "query": "Advertised : False, Withdrawn : True"
   }
  ]
 },
 "panels": [
  {
   "title": "Routes Advertised/Active",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n  count(*) as count,\n  rd\n  from l3vpn_rib\n  where\n    peer_hash_id in ($peer_hash)\n    and ('$rd' = '-' or rd = '$rd')\n    and iswithdrawn = false\n  group by rd\n"
    }
   ]
  },
  {
   "title": "Routes Withdrawn/Inactive",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select\n  count(*) as count,\n  rd\n  from l3vpn_rib\n  where\n    peer_hash_id in ($peer_hash)\n    and ('$rd' = '-' OR rd = '$rd')\n    and iswithdrawn = true\n  group by rd\n"
    }
   ]
  },
  {
   "title": "Looking Glass (RD = $rd)",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select distinct ip.*, \n    \tFIRST_VALUE(geo_ip.city) OVER (PARTITION BY ip.prefix ORDER BY geo_ip.ip DESC) as city,\n    \tFIRST_VALUE(geo_ip.stateprov) OVER (PARTITION BY ip.prefix ORDER BY geo_ip.ip DESC) as stateprov,\n    \tFIRST_VALUE(geo_ip.country) OVER (PARTITION BY ip.prefix ORDER BY geo_ip.ip DESC) as country,\n    ls.local_router_name\n\tFROM (SELECT lastmodified,peername,rd,prefix,\n        \tiswithdrawn,origin_as,med,localpref,nh,as_path,communities,extcommunities\n        from v_l3vpn_routes\n    \t\twhere \n    \t\t  peer_hash_id in ($peer_hash)\n    \t\t  AND ('$rd' = '-' OR rd = '$rd')\n    \t\t  AND (iswithdrawn in ($state))\n    \t\tlimit $limit\n    \t) ip\n\t\tLEFT JOIN geo_ip on (geo_ip.ip >>= ip.prefix AND geo_ip.ip != '0.0.0.0/0')\n    LEFT JOIN v_ls_prefixes ls ON (ls.prefix >>= ip.nh and length(ls.local_router_name) > 0)"
    }
   ]
  }
 ]
}