{
 "title": "Looking Glass",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prefix", "label": "Prefix", "query": "3.235.73.1" },
   {
    "name": "router_name",
    "label": "Router",
    "query": "select name from routers where state = 'up'"
   },
   {
    "name": "peer_name",
    "label": "Peer",
    "query": "select peername from v_peers where peer_state = 'up' and router_hash_id = '$router_hash'"
   },
   {
    "name": "router_hash",
    "query": "select hash_id from routers where name = '$router_name' limit 1"
   },
   {
    "name": "peer_hash",
    "query": "select peer_hash_id from v_peers where peername = '$peer_name' limit 1"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Looking Glass\n\n> Enter an IP address with or without bit length.  The longest matched prefix will be used. Specify the length to find exact match or best aggregate."
   }
  },
  {
   "title": "Prefix Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  10 as value, latitude, longitude, stateprov as name\nFROM geo_ip\nWHERE\n  ip && '[[prefix]]'\nORDER BY ip desc limit 1"
    }
   ]
  },
  {
   "title": "Router Visibility",
   "type": "grafana-piechart-panel",
   "description": "Prefix found in router's RIB.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(r.timestamp))) as time,\n  CASE WHEN v.router_hash_id is null THEN 'Not in Router RIB' ELSE 'In Router Rib' END as metric,\n  1 as value\nFROM routers r\n  left join (select distinct router_hash_id\n             from v_ip_routes \n             where prefix = (select prefix from ip_rib where prefix >>= '[[prefix]]' order by prefix_len desc limit 1)\n                and iswithdrawn = false group by router_hash_id) v \n            on (r.hash_id = v.router_hash_id)\nWHERE r.state = 'up'\nGROUP BY r.hash_id,v.router_hash_id\n\n"
    }
   ]
  },
  {
   "title": "Peer Visibility",
   "type": "grafana-piechart-panel",
   "description": "Prefix found in peer RIB's",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(p.timestamp))) as time,\n  CASE WHEN v.peer_hash_id is null THEN 'Not in Peers RIB' ELSE 'In Peer RIB' END as metric,\n  1 as value\nFROM bgp_peers p\n  left join (select peer_hash_id,isipv4\n             from v_ip_routes \n             where prefix >>= '[[prefix]]' \n                and iswithdrawn = false group by peer_hash_id,isipv4) v \n            on (p.hash_id = v.peer_hash_id)\nWHERE p.isipv4 = CASE WHEN family('[[prefix]]') = 4 THEN true ELSE false END\n  AND p.state = 'up'\nGROUP BY p.hash_id,v.peer_hash_id,p.isipv4\n\n"
    }
   ]
  },
  {
   "title": "ASN Info",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select distinct origin_as,i.as_name,org_id,org_name,remarks,address,city,state_prov,country,raw_output,source\n  from ip_rib r LEFT JOIN  info_asn i ON (i.asn = r.origin_as)\n  where r.prefix = (select prefix from ip_rib where prefix >>= '[[prefix]]' order by prefix desc limit 1) \n    and origin_as > 0\n"
    }
   ]
  },
  {
   "title": "Prefix Info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select distinct r.origin_as as recv_origin_as,\n    CASE WHEN g.rpki_origin_as is null THEN 0 ELSE g.rpki_origin_as END as rpki_origin_as,\n    CASE WHEN i.origin_as is null THEN 0 ELSE i.origin_as END as irr_origin_as,\n    i.descr,i.source\n  from ip_rib r \n    LEFT JOIN info_route i ON (i.prefix = r.prefix)\n    LEFT JOIN global_ip_rib g ON (g.prefix = r.prefix)\n  where r.prefix = (select prefix from ip_rib where prefix >>= '[[prefix]]' AND peer_hash_id = '$peer_hash' order by prefix desc limit 1)\n    and r.origin_as > 0\n    AND r.peer_hash_id = '$peer_hash'\n"
    }
   ]
  },
  {
   "title": "Looking Glass",
   "type": "table-old",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "--select ip.*, ls.local_router_name, geo_ip.city,geo_ip.stateprov,geo_ip.country\nselect distinct ip.*, ls.local_router_name\n\tFROM (SELECT lastmodified,peername,prefix,\n        \tiswithdrawn,origin_as,med,localpref,nh,as_path,communities,\n        \tgeo_ip.city,geo_ip.stateprov,geo_ip.country\n    \t\tfrom v_ip_routes\n    \t\tLEFT JOIN geo_ip on (geo_ip.ip >>= '[[prefix]]' AND geo_ip.ip != '0.0.0.0/0')\n    \t\twhere prefix && '[[prefix]]' and prefixlen <= 32 AND prefixlen > 0\n    \t\t  AND peer_hash_id = '$peer_hash'\n    \t\tlimit 2000\n    \t) ip\n    LEFT JOIN v_ls_prefixes ls ON (ls.prefix >>= ip.nh)"
    }
   ]
  }
 ]
}