{
 "title": "Looking Glass",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "input", "label": "Prefix/IP", "query": "3.235.73.1" },
   {
    "name": "router_hash",
    "label": "Router",
    "query": "select name as __text, hash_id as __value from routers where state = 'up'"
   },
   {
    "name": "peer_hash",
    "label": "Peer",
    "query": "select peername as __text, peer_hash_id as __value from v_peers where router_hash_id in ($router_hash)"
   },
   {
    "name": "prefix",
    "query": "select prefix from ip_rib \nwhere prefix >>= '$input' and peer_hash_id in ($peer_hash) \norder by prefix desc limit 1"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Looking Glass\n\n> Enter an IP address with or without bit length.  The longest matched prefix will be used. Specify the length to find exact match or best aggregate."
   }
  },
  {
   "title": "Prefix Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  10 as value, latitude, longitude, stateprov as name\nFROM geo_ip\nWHERE\n  ip && '$input'\nORDER BY ip desc limit 1"
    }
   ]
  },
  {
   "title": "Router Visibility",
   "type": "piechart",
   "description": "Prefix found in router's RIB.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(r.timestamp))) as time,\n  CASE WHEN v.router_hash_id is null THEN 'Not in Router RIB' ELSE 'In Router Rib' END as metric,\n  1 as value\nFROM routers r\n  left join (select distinct router_hash_id\n             from v_ip_routes \n             where prefix = '$prefix'\n                and iswithdrawn = false group by router_hash_id) v \n            on (r.hash_id = v.router_hash_id)\nWHERE r.state = 'up'\nGROUP BY r.hash_id,v.router_hash_id\norder by time\n\n"
    }
   ]
  },
  {
   "title": "Peer Visibility",
   "type": "piechart",
   "description": "Prefix found in peer RIB's",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(p.timestamp))) as time,\n  CASE WHEN v.peer_hash_id is null THEN 'Not in Peers RIB' ELSE 'In Peer RIB' END as metric,\n  1 as value\nFROM bgp_peers p\n  left join (select peer_hash_id,isipv4\n             from v_ip_routes \n             where prefix = '$prefix' and prefix != '0.0.0.0/0'\n                and iswithdrawn = false group by peer_hash_id,isipv4) v \n            on (p.hash_id = v.peer_hash_id)\nWHERE p.isipv4 = CASE WHEN family('$prefix') = 4 THEN true ELSE false END\n  AND p.state = 'up'\nGROUP BY p.hash_id,v.peer_hash_id,p.isipv4\norder by time\n\n"
    }
   ]
  },
  {
   "title": "ASN Info",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select distinct origin_as,i.as_name,org_id,org_name,remarks,address,city,state_prov,country,raw_output,source\n  from ip_rib r LEFT JOIN  info_asn i ON (i.asn = r.origin_as)\n  where r.prefix = '$prefix' \n    and origin_as > 0\n"
    }
   ]
  },
  {
   "title": "Prefix Info",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select distinct r.origin_as as recv_origin_as,\n    CASE WHEN g.rpki_origin_as is null THEN 0 ELSE g.rpki_origin_as END as rpki_origin_as,\n    CASE WHEN i.origin_as is null THEN 0 ELSE i.origin_as END as irr_origin_as,\n    i.descr,i.source\n  from ip_rib r \n    LEFT JOIN info_route i ON (i.prefix = r.prefix)\n    LEFT JOIN global_ip_rib g ON (g.prefix = r.prefix)\n  where r.prefix = '$prefix'\n    and r.origin_as > 0\n    AND r.peer_hash_id in ($peer_hash)\n"
    }
   ]
  },
  {
   "title": "Looking Glass",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select distinct ip.*, \n    \tFIRST_VALUE(geo_ip.city) OVER (PARTITION BY ip.prefix ORDER BY geo_ip.ip DESC) as city,\n    \tFIRST_VALUE(geo_ip.stateprov) OVER (PARTITION BY ip.prefix ORDER BY geo_ip.ip DESC) as stateprov,\n    \tFIRST_VALUE(geo_ip.country) OVER (PARTITION BY ip.prefix ORDER BY geo_ip.ip DESC) as country,\n    ls.local_router_name\n\tFROM (SELECT lastmodified,peername,prefix,\n        \tiswithdrawn,origin_as,med,localpref,nh,as_path,communities\n        from v_ip_routes\n    \t\twhere prefix && '$input' and prefixlen <= 32 AND prefixlen > 0\n    \t\t  AND peer_hash_id in ($peer_hash)\n    \t\tlimit 2000\n    \t) ip\n\t\tLEFT JOIN geo_ip on (geo_ip.ip >>= ip.prefix AND geo_ip.ip != '0.0.0.0/0')\n    LEFT JOIN v_ls_prefixes ls ON (ls.prefix >>= ip.nh and length(ls.local_router_name) > 0)"
    }
   ]
  }
 ]
}