{
 "title": "Prefix History (by ASN)",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "origin_as", "label": "Origin ASN", "query": "0" },
   { "name": "limit", "label": "Limit", "query": "1000,5000,10000" },
   {
    "name": "router_hash",
    "label": "Router",
    "query": "select name as __text, hash_id as __value from routers where state = 'up'"
   },
   {
    "name": "peer_hash",
    "label": "Peer",
    "query": "select peername as __text, peer_hash_id as __value from v_peers where router_hash_id in ($router_hash) and peer_state = 'up'"
   }
  ]
 },
 "panels": [
  {
   "title": "Prefix Advertisements & Withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(interval_time, $__interval) as time,\n  sum(updates) as updates, sum(withdraws) as withdraws\nFROM stats_chg_byasn s\nWHERE $__timeFilter(interval_time)\n   AND s.origin_as = [[origin_as]]\n   AND s.peer_hash_id in ($peer_hash)\n\ngroup by time\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Changes by Peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(interval_time, $__interval) as time,\n  sum(updates) as updates, sum(withdraws) as withdraws,\n  left(PeerName,32) as metric\nFROM stats_chg_byasn l\n  JOIN v_peers p ON (l.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n   AND l.origin_as = [[origin_as]]\n  AND l.peer_hash_id in ($peer_hash)\n\nGROUP BY peername,time\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "title": "Prefix History",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": " select lastmodified,event,routername,peername,prefix,nh,\n        origin_as,localpref,med,as_path,communities\n    from v_ip_routes_history \n    where  $__timeFilter(lastmodified)\n      AND origin_as = [[origin_as]]\n      AND peer_hash_id in ($peer_hash)\n\n    order by lastmodified desc,id desc\n    limit $limit;"
    }
   ]
  }
 ]
}