{
 "title": "Top by Prefixes",
 "tags": [ "obmp-tops" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router_hash",
    "label": "Filter by Router",
    "query": "select name as __text, hash_id as __value from routers where length(name) > 0"
   },
   {
    "name": "peer_hash",
    "label": "Peer",
    "query": "select peername as __text, peer_hash_id as __value from v_peers where router_hash_id in ($router_hash)"
   }
  ]
 },
 "panels": [
  {
   "title": "Advertisements & Withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(interval_time, $__interval) as time,\n   sum(updates) as updates,sum(withdraws) as withdraws\nFROM stats_chg_bypeer s\n  JOIN v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n  AND s.peer_hash_id in ($peer_hash)\nGROUP BY time\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "title": "Updates by Router",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(interval_time, $__interval) as time,\n    sum(updates),\n    p.routername as metric\n  FROM stats_chg_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND l.peer_hash_id in ($peer_hash)\n  GROUP BY routername,time\n  order by time asc\n"
    }
   ]
  },
  {
   "title": "Withdraws  by Peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(interval_time, $__interval) as time,\n    sum(withdraws),\n    p.routername as metric\n  FROM stats_chg_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND l.peer_hash_id in ($peer_hash)\n  group by routername,time\n  order by time"
    }
   ]
  },
  {
   "title": "Updates by Peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(interval_time, $__interval) as time,\n    sum(updates),\n    p.PeerName as metric\n  FROM stats_chg_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND l.peer_hash_id in ($peer_hash)\n  GROUP BY peername,time\n  order by time asc\n"
    }
   ]
  },
  {
   "title": "Withdraws  by Peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(interval_time, $__interval) as time,\n    sum(withdraws),\n    p.PeerName as metric\n  FROM stats_chg_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND l.peer_hash_id in ($peer_hash)\n  group by peername,time\n  order by time"
    }
   ]
  },
  {
   "title": "Top  Updates by ASN",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT as_name as \"AS Name\",d.* from (\n  SELECT\n      origin_as as asn,\n      sum(updates) as \"Updates\"\n    FROM stats_chg_byasn l\n    WHERE $__timeFilter(interval_time)\n        AND peer_hash_id in ($peer_hash)\n    GROUP BY asn\n    order by \"Updates\" desc\n  LIMIT 20\n) d\nLEFT JOIN info_asn i ON (i.asn = d.asn)\n"
    }
   ]
  },
  {
   "title": "Top  Withdraws by ASN",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT as_name,d.* from (\n  SELECT\n      origin_as as asn,\n      sum(withdraws) as \"Withdraws\"\n    FROM stats_chg_byasn l\n    WHERE $__timeFilter(interval_time)\n        AND peer_hash_id in ($peer_hash)\n    GROUP BY asn\n    order by \"Withdraws\" desc\n  LIMIT 20\n) d\nLEFT JOIN info_asn i ON (i.asn = d.asn)\n"
    }
   ]
  },
  {
   "title": "Top Prefix Updates",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT as_name as \"AS Name\", irr_descr as \"Desc\",r.recv_origin_as as origin_as,d.* FROM (\nSELECT\n    prefix,\n    sum(updates) as \"Updates\"\n  FROM stats_chg_byprefix l\n  WHERE $__timeFilter(interval_time)\n      AND peer_hash_id in ($peer_hash)\n  GROUP BY prefix\n  order by \"Updates\" desc\nLIMIT 60\n) d\nJOIN global_ip_rib r ON (r.prefix = d.prefix)\nLEFT JOIN info_asn i ON (i.asn = r.recv_origin_as)"
    }
   ]
  },
  {
   "title": "Top Prefix Withdraws",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT as_name as \"AS Name\", irr_descr as \"Desc\",r.recv_origin_as as origin_as,d.* FROM (\nSELECT\n    prefix,\n    sum(withdraws) as \"Withdraws\"\n  FROM stats_chg_byprefix l\n  WHERE $__timeFilter(interval_time)\n      AND peer_hash_id in ($peer_hash)\n  GROUP BY prefix\n  order by \"Withdraws\" desc\nLIMIT 60\n) d\nJOIN global_ip_rib r ON (r.prefix = d.prefix)\n--LEFT JOIN info_route ir ON (ir.prefix = d.prefix)\nLEFT JOIN info_asn i ON (i.asn = r.recv_origin_as)"
    }
   ]
  }
 ]
}