{
 "title": "Top L3VPN by Prefixes",
 "tags": [ "obmp-tops" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "router_hash",
    "label": "Filter by Router",
    "query": "select routername as __text, router_hash_id as __value from v_peers where router_state = 'up' and  recvcapabilities like '% afi=1 safi=128 %';"
   },
   {
    "name": "peer_hash",
    "label": "Peer",
    "query": "select peername as __text, peer_hash_id as __value from v_peers where router_hash_id in ($router_hash) and  recvcapabilities like '% afi=1 safi=128 %';"
   }
  ]
 },
 "panels": [
  {
   "title": "Advertisements & Withdrawals",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(interval_time, $__interval) as time,\n   sum(updates) as updates,sum(withdraws) as withdraws\nFROM stats_l3vpn_chg_bypeer s\n  JOIN v_peers p ON (s.peer_hash_id = p.peer_hash_id)\nWHERE $__timeFilter(interval_time)\n  AND s.peer_hash_id in ($peer_hash)\nGROUP BY time\nORDER BY time ASC\n\n"
    }
   ]
  },
  {
   "title": "Updates by Peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(interval_time, $__interval) as time,\n    sum(updates),\n    p.PeerName as metric\n  FROM stats_l3vpn_chg_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND l.peer_hash_id in ($peer_hash)\n  GROUP BY peername,time\n  order by time asc\n"
    }
   ]
  },
  {
   "title": "Withdraws  by Peer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    $__timeGroup(interval_time, $__interval) as time,\n    sum(withdraws),\n    p.PeerName as metric\n  FROM stats_l3vpn_chg_bypeer l\n  JOIN v_peers p ON (p.peer_hash_id = l.peer_hash_id)\n  WHERE $__timeFilter(interval_time)\n     AND l.peer_hash_id in ($peer_hash)\n  group by peername,time\n  order by time"
    }
   ]
  },
  {
   "title": "Top  Updates by RD",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "  SELECT\n      rd,\n      sum(updates) as \"Updates\"\n    FROM stats_l3vpn_chg_byrd l\n    WHERE $__timeFilter(interval_time)\n        AND peer_hash_id in ($peer_hash)\n    GROUP BY rd\n    order by \"Updates\" desc\n  LIMIT 20"
    }
   ]
  },
  {
   "title": "Top  Withdraws by RD",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "  SELECT\n      rd,\n      sum(withdraws) as \"Withdraws\"\n    FROM stats_l3vpn_chg_byrd l\n    WHERE $__timeFilter(interval_time)\n        AND peer_hash_id in ($peer_hash)\n    GROUP BY rd\n    order by \"Withdraws\" desc\n  LIMIT 20"
    }
   ]
  },
  {
   "title": "Top Prefix Updates",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    rd,prefix,\n    sum(updates) as \"Updates\"\n  FROM stats_l3vpn_chg_byprefix l\n  WHERE $__timeFilter(interval_time)\n      AND peer_hash_id in ($peer_hash)\n  GROUP BY rd,prefix\n  order by \"Updates\" desc\nLIMIT 60\n"
    }
   ]
  },
  {
   "title": "Top Prefix Withdraws",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\n    rd,prefix,\n    sum(withdraws) as \"Withdraws\"\n  FROM stats_l3vpn_chg_byprefix l\n  WHERE $__timeFilter(interval_time)\n      AND peer_hash_id in ($peer_hash)\n  GROUP BY rd,prefix\n  order by \"Withdraws\" desc\nLIMIT 60\n"
    }
   ]
  }
 ]
}