{
 "title": "Peer Analysis",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "> MRT2BMP has an issue with **IPv6** RIB dumps. IPv6 RIB tables are valid when seen via UPDATES (e.g. peer reset, refresh, or over time)\n\n*MRT2BMP will be updated to fix this*"
  },
  {
   "title": "Peers by State",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(timestamp))) as time,\n  count(*) as value,\n  state as metric\nFROM bgp_peers\n  group by metric"
    }
   ]
  },
  {
   "title": "IPv4 Peer RIB Sizes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n    floor(extract(epoch from last(interval_time,interval_time))) as time,\n    CASE WHEN v4_prefixes > 700000 THEN 'full (> 700k)' \n            WHEN v4_prefixes > 300000 THEN 'partial (> 300K)'\n            WHEN v4_prefixes > 100000 THEN 'weak (> 100K)'\n            WHEN v4_prefixes > 9000 THEN 'poor (> 9k)'\n            ELSE 'customer_only (< 9K)'\n        END as rib_class,\n    count(distinct peer_hash_id) as count\nFROM stats_peer_rib s\n  JOIN bgp_peers p ON (p.hash_id = s.peer_hash_id)\nWHERE interval_time >= now() - interval '40 minute'\n  AND p.isipv4 = true\nGROUP BY rib_class\nORDER BY count desc\n\n"
    }
   ]
  },
  {
   "title": "Peers by AFI",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  floor(extract(epoch from max(timestamp))) as time,\n  count(*) as value,\n  CASE WHEN isIPv4 THEN 'IPv4' ELSE 'IPv6' END as metric\nFROM bgp_peers\n  group by metric"
    }
   ]
  },
  {
   "title": "IPv6 Peer RIB Sizes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n    floor(extract(epoch from last(interval_time,interval_time))) as time,\n    CASE WHEN v6_prefixes > 50000 THEN 'full (> 50K)' \n            WHEN v6_prefixes > 20000 THEN 'partial (> 20K)'\n            WHEN v6_prefixes > 10000 THEN 'weak (> 10K)'\n            WHEN v6_prefixes > 1000 THEN 'poor (> 1k)'\n            ELSE 'customer_only (< 1K)'\n        END as rib_class,\n    count(distinct peer_hash_id) as count\nFROM stats_peer_rib s\n  JOIN bgp_peers p ON (p.hash_id = s.peer_hash_id)\nWHERE interval_time >= now() - interval '40 minute'\n  AND p.isipv4 = false\nGROUP BY rib_class\nORDER BY count desc\n\n"
    }
   ]
  },
  {
   "title": "Peer Rank",
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT  DENSE_RANK() OVER (PARTITION BY peer_ipv ORDER BY ((transit_connections * 2) + connections) desc) as rank,\n       peer_ipv, \"RouterName\",\"PeerASN\",\"PeerName\",\"AS Name\",\n      rib_class,update_class,withdraw_class,connections,transit_connections\n  FROM v_peers_class\n  WHERE rib_class = 'full' AND update_class = 'normal' AND withdraw_class = 'normal' and \"State\" = 'up'\n  ORDER BY peer_ipv,rank;"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }, "content": "---" }
 ]
}